window.JETFOR_DASH = {
 "fleet": [
  {"mat":"PR-ARN","modelo":"Beechcraft B200GT","fab":"Beechcraft","tcds":"EM-8005-13","assentos":"10+ (confirmar)","enq":"135.411(a)(2)","sasc":true,"obs":"Entra no SASC/PMAC","mapa":null},
  {"mat":"(em inclusão)","modelo":"Cessna Citation 550","fab":"Cessna","tcds":"EM-8403-02","assentos":"10+ (confirmar)","enq":"135.411(a)(2)","sasc":true,"obs":"Em processo de inclusão","mapa":null},
  {"mat":"PT-LJQ","modelo":"Cessna Citation S550","fab":"Cessna","tcds":"EM-8403 (confirmar)","assentos":"10+ (confirmar)","enq":"135.411(a)(2)","sasc":true,"obs":"S/N S550-0113 · em inclusão no SASC","mapa":"PT-LJQ"},
  {"mat":"PR-LJA (confirmar)","modelo":"Embraer EMB-505 (Phenom 300)","fab":"Embraer","tcds":"EA-2009T12","assentos":"até 10 (tipo cert. 11 ocup.)","enq":"135.411(a)(2)","sasc":true,"obs":"SASC pela certificação de tipo (até 10 assentos pax)","mapa":null},
  {"mat":"PP-LCB","modelo":"Beechcraft King Air 200 (A200)","fab":"Beechcraft","tcds":"EM-8005-13","assentos":"8 (config. aprovada)","enq":"135.411(a)(1)","sasc":false,"obs":"Mesmo tipo do B200GT, config. ≤9","mapa":null},
  {"mat":"PP-SCF","modelo":"Beechcraft King Air C90","fab":"Beechcraft","tcds":"a levantar","assentos":"5 (config.)","enq":"135.411(a)(1)","sasc":false,"obs":"≤9 assentos","mapa":null},
  {"mat":"PS-ALT","modelo":"Beechcraft King Air C90A","fab":"Beechcraft","tcds":"a levantar","assentos":"≤9 (confirmar)","enq":"135.411(a)(1)","sasc":false,"obs":"PMAC/SASC cancelados 2022 (isenção IS 120-016 rev B)","mapa":null},
  {"mat":"PR-AEX","modelo":"Hawker 400A (Beechjet 400)","fab":"Hawker","tcds":"a levantar","assentos":"≤9 (confirmar)","enq":"135.411(a)(1)","sasc":false,"obs":"≤9 assentos","mapa":null}
 ],
 "modeloOperacional":"A JetFor é OPERADORA e faz o CONTROLE da aeronavegabilidade continuada (papel tipo CAMO). Não executa manutenção: não possui ferramental nem estoque próprios. Toda a manutenção prática (serviços, calibrações, inspeções físicas, pesagem) é executada por OFICINAS certificadas RBAC 145 contratadas — a JetFor programa, controla os prazos, exige os comprovantes e audita os fornecedores.",
 "atividades": [
  {"atv":"Consulta de Diretrizes de Aeronavegabilidade (AD/DA)","freq":"Diária","base":"RBAC 91 · FCDA","escopo":"Geral","resp":"JetFor",
   "como":"Todo dia útil, acessar o sistema de DA da ANAC e as fontes do estado de projeto (FAA AD / EASA AD) e do fabricante. Verificar se saiu nova DA/AD aplicável ao tipo (S550) e aos componentes/motores. Registrar a consulta na FCDA (Ficha de Controle de DA) com data e responsável — inclusive quando não há emissão nova (\"sem novidade\"). Havendo DA aplicável, abrir o item no planejamento e encaminhar a execução à oficina 145."},
  {"atv":"Verificação de emissão de Boletins de Serviço (SB)","freq":"Mensal","base":"FCDA","escopo":"Geral","resp":"JetFor",
   "como":"Mensalmente, consultar os portais dos fabricantes (Textron/Cessna 1View, Pratt & Whitney) por novos Boletins de Serviço. Avaliar aplicabilidade ao S/N da aeronave e dos motores; classificar (mandatório × recomendado). Encaminhar os aplicáveis ao planejamento (execução na oficina 145) e registrar a verificação."},
  {"atv":"Verificação/atualização da Biblioteca Técnica","freq":"Mensal","base":"IS 119-004","escopo":"Geral","resp":"JetFor",
   "como":"Conferir se todos os manuais de referência da JetFor (MGM, PMA, MEL, listas de DA/SB, AMM/IPC de consulta) estão na revisão vigente. Baixar as revisões novas, registrar a revisão em vigor e a data, e arquivar/segregar as versões obsoletas para não haver uso indevido."},
  {"atv":"Controle de itens com prazo de validade (shelf life)","freq":"Mensal","base":"IS 43-001","escopo":"Geral","resp":"Oficina 145 + JetFor",
   "como":"A JetFor NÃO mantém estoque próprio — o controle de shelf life de consumáveis (selantes, O-rings, adesivos) é da oficina 145 contratada. A JetFor controla apenas a validade dos itens INSTALADOS na aeronave (extintores, bateria/cartucho do ELT, cartuchos de coletes/botes, cilindros de O2) pelo mapa de controle, e exige da oficina os comprovantes na entrega do serviço."},
  {"atv":"Calibração de ferramentas e instrumentos de medição","freq":"12 meses","base":"MGM cap. 4","escopo":"Geral","resp":"Oficina 145",
   "como":"A JetFor NÃO possui ferramental próprio. A calibração de torquímetros e instrumentos é responsabilidade da oficina 145 que executa os serviços. O papel da JetFor é verificar, na auditoria anual de fornecedor, se a oficina mantém as ferramentas calibradas por laboratório acreditado (RBC/INMETRO) e guardar cópia dos certificados no dossiê do fornecedor."},
  {"atv":"Inspeção de equipamentos de emergência (pirotécnicos, botes)","freq":"Anual","base":"RBAC 135.166 / 91.205","escopo":"Geral","resp":"Oficina 145 + JetFor",
   "como":"A inspeção/recarga física (coletes, botes, extintores, ELT) é feita por oficina/empresa especializada. A JetFor controla os prazos de validade no mapa, programa o envio antes do vencimento e arquiva os laudos/certificados recebidos."},
  {"atv":"Pesagem / peso e balanceamento","freq":"36 meses","base":"RBAC 135.185","escopo":"Geral","resp":"Oficina 145",
   "como":"A pesagem e o relatório de peso e balanceamento são executados por oficina habilitada. A JetFor controla o prazo (36 meses ou após grande alteração), recebe e arquiva o relatório e mantém a ficha de peso vazio/CG operacional atualizada (aprovação SEI/ANAC quando aplicável)."},
  {"atv":"FISTEL (taxa) + Licença de Estação (ANATEL)","freq":"Anual","base":"MGM cap. 1","escopo":"Geral","resp":"JetFor",
   "como":"Manter em dia a taxa FISTEL e a Licença de Estação de Aeronave junto à ANATEL. Pagar antes do vencimento e guardar os comprovantes no registro da aeronave (e a bordo, se exigido). Tarefa administrativa da JetFor."},
  {"atv":"RDS — Relatório de Dificuldades em Serviço","freq":"Por evento","base":"RBAC 135.415 · IS 00-001","escopo":"Geral","resp":"JetFor",
   "como":"Ao ocorrer uma dificuldade em serviço reportável (falha, mau funcionamento ou defeito listado no apêndice da IS 00-001), a JetFor preenche e envia o RDS à ANAC dentro do prazo, pelo sistema SDR. Registrar internamente o evento, a análise e a ação tomada (com apoio da oficina que fez o reparo)."},
  {"atv":"Cumprimento de AD/DA e SB aplicáveis (FCDA)","freq":"Contínuo","base":"RBAC 91 / 43","escopo":"Geral","resp":"JetFor + Oficina 145",
   "como":"A JetFor incorpora as DA/AD e SB aplicáveis à programação e envia para a oficina 145 executar. Recebe o registro de cumprimento (retorno ao serviço) com os dados (data, TSN/TSO, método), confere e atualiza a FCDA e o mapa de controle (VENC/DISP)."},
  {"atv":"Componentes com vida-limite / TBO","freq":"Contínuo (PMA)","base":"PMA do modelo","escopo":"Geral","resp":"JetFor + Oficina 145",
   "como":"A JetFor controla os componentes com limite de vida (LLP) e TBO conforme o PMA do modelo, acompanhando horas/ciclos/calendário no mapa. Programa a remoção/overhaul com folga antes do limite; a execução (remoção/instalação/overhaul) é feita pela oficina 145."},
  {"atv":"Itens de Inspeção Obrigatória (IIO) — aceitação por inspetor","freq":"Por evento de manut.","base":"MGM 2.8 · IS 120-016","escopo":"SASC","resp":"Oficina 145",
   "como":"A JetFor define no MGM (item 2.8) a lista de IIO/RII — itens críticos cujo erro pode afetar a segurança. Na oficina 145, após a execução, um inspetor qualificado e independente de quem executou inspeciona e aceita o item antes do retorno ao serviço. A JetFor confere a dupla inspeção nos registros recebidos."},
  {"atv":"RSI — Relatório Sumário de Interrupção Mecânica","freq":"Mensal (até 10º dia útil)","base":"RBAC 135.417","escopo":"SASC","resp":"JetFor",
   "como":"A JetFor consolida as interrupções mecânicas do mês (cancelamentos, retornos ao solo, panes com impacto operacional) e envia o RSI à ANAC até o 10º dia útil do mês seguinte, conforme 135.417. Obrigatório apenas para a frota SASC (10+ assentos)."},
  {"atv":"Coleta e análise de dados de confiabilidade","freq":"Mensal / contínua","base":"MGM 5.6 · IS 120-016","escopo":"SASC","resp":"JetFor",
   "como":"A JetFor coleta continuamente os dados (panes, remoções, discrepâncias, consumo de óleo, atrasos — muitos vindos dos relatórios das oficinas) e alimenta o sistema de confiabilidade do SASC. Calcula as taxas (por 1000h/ciclos) por sistema (ATA) e compara com os níveis de alerta."},
  {"atv":"Reunião do Comitê SASC","freq":"Trimestral","base":"MGM 5.6 · IS 120-016","escopo":"SASC","resp":"JetFor",
   "como":"Reunir trimestralmente o Comitê SASC (direção de manutenção, qualidade, confiabilidade) para analisar indicadores, itens acima do nível de alerta e ações corretivas. Registrar em ata (formulário F-SASC-01) com decisões e responsáveis."},
  {"atv":"Avaliação anual do SASC","freq":"Anual","base":"MGM 5.6 · IS 120-016","escopo":"SASC","resp":"JetFor",
   "como":"Uma vez por ano, avaliar a eficácia do programa SASC: revisar níveis de alerta, ações tomadas e resultados obtidos. Documentar no formulário F-SASC-03 e reportar à direção (e à ANAC quando aplicável), conforme MGM 5.6."},
  {"atv":"Auditorias internas e de fornecedores (SASC)","freq":"Anual","base":"MGM 5.6","escopo":"SASC","resp":"JetFor",
   "como":"Ponto-chave no modelo da JetFor: auditar anualmente as OFICINAS 145 contratadas — certificação vigente, escopo (EO), capacitação, ferramentas calibradas, controle de estoque/shelf life e qualidade dos registros. Emitir relatório com não-conformidades e plano de ação (formulário F-SASC-02) e acompanhar o fechamento."},
  {"atv":"Análise de níveis de alerta / relatório de confiabilidade","freq":"Periódico","base":"MGM 5.6 · IS 120-016","escopo":"SASC","resp":"JetFor",
   "como":"Calcular/revisar periodicamente os níveis de alerta por sistema (ATA) a partir do histórico. Quando um sistema ultrapassa o nível, abrir investigação, definir ação corretiva (com a oficina, se for o caso) e registrar no relatório de confiabilidade do SASC."}
 ]
};
