window.JETFOR_DASH = {
 "fleet": [
  {"mat":"PR-ARN","modelo":"Beechcraft B200GT","fab":"Beechcraft","tcds":"EM-8005-13","assentos":"10+ (confirmar)","enq":"135.411(a)(2)","sasc":true,"obs":"Entra no SASC/PMAC","mapa":null},
  {"mat":"(em inclusão)","modelo":"Cessna Citation 550","fab":"Cessna","tcds":"EM-8403-02","assentos":"10+ (confirmar)","enq":"135.411(a)(2)","sasc":true,"obs":"Em processo de inclusão","mapa":null},
  {"mat":"PT-LJQ","modelo":"Cessna Citation S550","fab":"Cessna","tcds":"EM-8403 (confirmar)","assentos":"10+ (confirmar)","enq":"135.411(a)(2)","sasc":true,"obs":"S/N S550-0113 · em inclusão no SASC","mapa":"PT-LJQ"},
  {"mat":"PR-LJA (confirmar)","modelo":"Embraer EMB-505 (Phenom 300)","fab":"Embraer","tcds":"EA-2009T12","assentos":"até 10 (tipo cert. 11 ocup.)","enq":"135.411(a)(2)","sasc":true,"obs":"SASC pela certificação de tipo (até 10 assentos pax)","mapa":null},
  {"mat":"PP-LCB","modelo":"Beechcraft King Air 200 (A200)","fab":"Beechcraft","tcds":"EM-8005-13","assentos":"8 (config. aprovada)","enq":"135.411(a)(1)","sasc":false,"obs":"Mesmo tipo do B200GT, config. ≤9","mapa":null},
  {"mat":"PP-SCF","modelo":"Beechcraft King Air C90","fab":"Beechcraft","tcds":"a levantar","assentos":"5 (config.)","enq":"135.411(a)(1)","sasc":false,"obs":"≤9 assentos","mapa":null},
  {"mat":"PS-ALT","modelo":"Beechcraft King Air C90A","fab":"Beechcraft","tcds":"a levantar","assentos":"≤9 (confirmar)","enq":"135.411(a)(1)","sasc":false,"obs":"PMAC/SASC cancelados 2022 (isenção IS 120-016 rev B)","mapa":null},
  {"mat":"PR-AEX","modelo":"Hawker 400A (Beechjet 400)","fab":"Hawker","tcds":"a levantar","assentos":"≤9 (confirmar)","enq":"135.411(a)(1)","sasc":false,"obs":"≤9 assentos","mapa":null}
 ],
 "atividades": [
  {"atv":"Consulta de Diretrizes de Aeronavegabilidade (AD/DA)","freq":"Diária","base":"RBAC 91 · FCDA","escopo":"Geral",
   "como":"Todo dia útil, acessar o sistema de DA da ANAC e as fontes do estado de projeto (FAA AD / EASA AD) e do fabricante. Verificar se saiu nova DA/AD aplicável ao tipo (S550) e aos componentes/motores. Registrar a consulta na FCDA (Ficha de Controle de DA) com data e responsável — inclusive quando não há emissão nova (\"sem novidade\"). Havendo DA aplicável, abrir o item no planejamento e no mapa de controle."},
  {"atv":"Verificação de emissão de Boletins de Serviço (SB)","freq":"Mensal","base":"FCDA","escopo":"Geral",
   "como":"Mensalmente, consultar os portais dos fabricantes (Textron/Cessna 1View, Pratt & Whitney) por novos Boletins de Serviço. Avaliar aplicabilidade ao S/N da aeronave e dos motores; classificar (mandatório × recomendado). Encaminhar os aplicáveis ao planejamento e registrar a verificação (data, responsável, SBs analisados)."},
  {"atv":"Verificação/atualização da Biblioteca Técnica","freq":"Mensal","base":"IS 119-004","escopo":"Geral",
   "como":"Conferir se todos os manuais (AMM/MM, IPC, WDM, MGM, PMA, MEL, SRM, etc.) estão na revisão vigente. Baixar as revisões novas, registrar a revisão em vigor e a data, e arquivar/segregar as versões obsoletas para não haver uso indevido."},
  {"atv":"Controle de itens com prazo de validade (shelf life)","freq":"Mensal","base":"IS 43-001","escopo":"Geral",
   "como":"Revisar a planilha de shelf life (selantes, adesivos, O-rings, cartuchos pirotécnicos, extintores, cilindros de oxigênio, baterias). Checar validades, segregar/identificar itens vencidos, e repor estoque com antecedência. Atualizar datas e lotes no controle."},
  {"atv":"Calibração de ferramentas e instrumentos de medição","freq":"12 meses","base":"MGM cap. 4","escopo":"Geral",
   "como":"Manter inventário das ferramentas que exigem calibração (torquímetros, manômetros, multímetros, paquímetros). Enviar a laboratório acreditado (RBC/INMETRO) antes do vencimento; arquivar os certificados rastreáveis e etiquetar cada item com a validade da calibração."},
  {"atv":"Inspeção de equipamentos de emergência (pirotécnicos, botes)","freq":"Anual","base":"RBAC 135.166 / 91.205","escopo":"Geral",
   "como":"Inspecionar/testar coletes e botes salva-vidas, ELT, extintores de cabine, kit de primeiros socorros e lanternas. Verificar validade de cartuchos pirotécnicos e da bateria do ELT, e testar o ELT conforme 91.207. Registrar as validades e o resultado da inspeção."},
  {"atv":"Pesagem / peso e balanceamento","freq":"36 meses","base":"RBAC 135.185","escopo":"Geral",
   "como":"A cada 36 meses (ou após grande alteração), realizar a pesagem por oficina habilitada e emitir o relatório de peso e balanceamento conforme a norma vigente. Atualizar a ficha de peso vazio/CG operacional e aprovar o documento (SEI/ANAC quando aplicável)."},
  {"atv":"FISTEL (taxa) + Licença de Estação (ANATEL)","freq":"Anual","base":"MGM cap. 1","escopo":"Geral",
   "como":"Manter em dia a taxa FISTEL e a Licença de Estação de Aeronave junto à ANATEL. Pagar antes do vencimento e guardar os comprovantes no registro da aeronave (e a bordo, se exigido)."},
  {"atv":"RDS — Relatório de Dificuldades em Serviço","freq":"Por evento","base":"RBAC 135.415 · IS 00-001","escopo":"Geral",
   "como":"Ao ocorrer uma dificuldade em serviço reportável (falha, mau funcionamento ou defeito listado no apêndice da IS 00-001), preencher e enviar o RDS à ANAC dentro do prazo, pelo sistema SDR. Registrar internamente o evento, a análise e a ação tomada."},
  {"atv":"Cumprimento de AD/DA e SB aplicáveis (FCDA)","freq":"Contínuo","base":"RBAC 91 / 43","escopo":"Geral",
   "como":"Incorporar as DA/AD e SB aplicáveis à programação; executar por oficina certificada (RBAC 145) e registrar o cumprimento (retorno ao serviço) com os dados (data, TSN/TSO, método). Atualizar a FCDA e o mapa de controle (VENC/DISP)."},
  {"atv":"Componentes com vida-limite / TBO","freq":"Contínuo (PMA)","base":"PMA do modelo","escopo":"Geral",
   "como":"Controlar os componentes com limite de vida (LLP) e TBO conforme o PMA do modelo. Acompanhar horas/ciclos/calendário no mapa de controle e programar remoção ou overhaul com folga antes de atingir o limite — evitando estouro de DISP."},
  {"atv":"Itens de Inspeção Obrigatória (IIO) — aceitação por inspetor","freq":"Por evento de manut.","base":"MGM 2.8 · IS 120-016","escopo":"SASC",
   "como":"Definir a lista de IIO/RII no MGM (item 2.8) — itens críticos cujo erro pode afetar a segurança. Após a execução, um inspetor qualificado e independente de quem executou deve inspecionar e aceitar o item antes do retorno ao serviço. Registrar a dupla inspeção (executante × inspetor)."},
  {"atv":"RSI — Relatório Sumário de Interrupção Mecânica","freq":"Mensal (até 10º dia útil)","base":"RBAC 135.417","escopo":"SASC",
   "como":"Consolidar as interrupções mecânicas do mês (cancelamentos, retornos ao solo, panes com impacto operacional) e enviar o RSI à ANAC até o 10º dia útil do mês seguinte, conforme 135.417. Obrigatório apenas para a frota SASC (10+ assentos)."},
  {"atv":"Coleta e análise de dados de confiabilidade","freq":"Mensal / contínua","base":"MGM 5.6 · IS 120-016","escopo":"SASC",
   "como":"Coletar continuamente os dados (panes, remoções, discrepâncias, consumo de óleo, atrasos) e alimentar o sistema de confiabilidade do SASC. Calcular as taxas (por 1000h/ciclos) por sistema (ATA) e comparar com os níveis de alerta definidos."},
  {"atv":"Reunião do Comitê SASC","freq":"Trimestral","base":"MGM 5.6 · IS 120-016","escopo":"SASC",
   "como":"Reunir trimestralmente o Comitê SASC (manutenção, qualidade, confiabilidade) para analisar indicadores, itens acima do nível de alerta e ações corretivas em andamento. Registrar em ata (formulário F-SASC-01) com decisões e responsáveis."},
  {"atv":"Avaliação anual do SASC","freq":"Anual","base":"MGM 5.6 · IS 120-016","escopo":"SASC",
   "como":"Uma vez por ano, avaliar a eficácia do programa SASC: revisar níveis de alerta, ações tomadas e resultados obtidos. Documentar no formulário F-SASC-03 e reportar à direção (e à ANAC quando aplicável), conforme MGM 5.6."},
  {"atv":"Auditorias internas e de fornecedores (SASC)","freq":"Anual","base":"MGM 5.6","escopo":"SASC",
   "como":"Auditar anualmente os processos internos de manutenção e as oficinas contratadas (RBAC 145): conformidade, capacitação, registros e controle de qualidade. Emitir relatório com não-conformidades e plano de ação (formulário F-SASC-02) e acompanhar o fechamento."},
  {"atv":"Análise de níveis de alerta / relatório de confiabilidade","freq":"Periódico","base":"MGM 5.6 · IS 120-016","escopo":"SASC",
   "como":"Calcular/revisar periodicamente os níveis de alerta por sistema (ATA) a partir do histórico. Quando um sistema ultrapassa o nível, abrir investigação, definir ação corretiva e registrar tudo no relatório de confiabilidade do SASC."}
 ]
};
