/* JetFor · patch de itens faltantes por aeronave (idempotente por nome) */
window.JETFOR_PATCH = {
 "PR-ARN": [
  {
   "grupo": "ITENS DE SERVIÇOS GERAIS",
   "categoria": "celula",
   "unidade": null,
   "nome": "EDGELIGHTED PANEL ASSY - INSPECTION",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 2000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-001"
  },
  {
   "grupo": "ITENS DE SERVIÇOS GERAIS",
   "categoria": "celula",
   "unidade": null,
   "nome": "ENGINE FIRE EXTINGUISHER BOTTTLE",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 60,
    "exec": null
   },
   "id": "PX-PRARN-002"
  },
  {
   "grupo": "ITENS DE SERVIÇOS GERAIS",
   "categoria": "celula",
   "unidade": null,
   "nome": "ENGINE FIRE EXTINGUISHER CARTRIDGE (SQUIB)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 72,
    "exec": null
   },
   "id": "PX-PRARN-003"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "ACTUATORS - MECHANICAL (ATUADORES MECÂNICOS) REVISÃO GERAL",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 8000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-004"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "motor",
   "unidade": null,
   "nome": "LANDING GEAR MOTOR - MECHANICAL (MOTOR DO TREM DE POUSO - MECÂNICO)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 8000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-005"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "NOSE AND MAIN LANDING GEAR ACTUATOR - INSPECTION",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 1000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-006"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "NOSE LANDING GEAR ACTUATOR LUBRIFICATION",
   "pn": "112-380022-21",
   "sn": "2581",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 1000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-007"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "MAIN LANDING GEAR ACTUATOR LUBRIFICATION",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 1000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-008"
  },
  {
   "grupo": "52 - DOOR",
   "categoria": "celula",
   "unidade": null,
   "nome": "WINDSHIELD FRAME SCREEWS",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 10000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-009"
  },
  {
   "grupo": "53 - FUSELAGE",
   "categoria": "celula",
   "unidade": null,
   "nome": "FUSELAGE STRINGER INSPECTION (A) (B) (C) (D) (E)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 2500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-010"
  },
  {
   "grupo": "53 - FUSELAGE",
   "categoria": "celula",
   "unidade": null,
   "nome": "FLIGHT CONTROL SYSTEMS WITHIN THE FUSELAGE PRESSURE VESSEL",
   "pn": "",
   "sn": "",
   "obs": "MTX",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 200,
   "exec": 1660.1,
   "vencFixo": null,
   "id": "PX-PRARN-011"
  },
  {
   "grupo": "57 - WINGS",
   "categoria": "celula",
   "unidade": null,
   "nome": "WING CENTER SECTION AND OUTBOARD WING",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 9500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-012"
  },
  {
   "grupo": "57 - WINGS",
   "categoria": "celula",
   "unidade": null,
   "nome": "WING CENTER SECTION",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 18000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-013"
  },
  {
   "grupo": "REPLACE LH/RH OUTBOARD WING SPAR",
   "categoria": "celula",
   "unidade": null,
   "nome": "OUTBOARD WING STRUCTURE",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 30000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-014"
  },
  {
   "grupo": "REPLACE LH/RH OUTBOARD WING SPAR",
   "categoria": "celula",
   "unidade": null,
   "nome": "WING AND ASSOCIATED STRUCTURE FATIGUE SAFELIFE",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 30000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-015"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "IF SUNDSTRAND FUEL PUMP INSTALLED: CHECK FUEL PUMP COUPLING IN-SITU FOR FRETTING AND CORROSION (LH) TABELA 601",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 600,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-016"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "IF SUNDSTRAND FUEL PUMP INSTALLED: CHECK FUEL PUMP COUPLING IN-SITU FOR FRETTING AND CORROSION (RH) TABELA 601",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor2_tsn",
   "tipoVenc": "horas",
   "intervalo": 600,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-017"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "IF SUNDSTRAND FUEL PUMP. REMOVE FUEL PUMP AND INSPECT THE DRIVE COUPLING AND COVER (ACESSORY GEARBOX SIDE) FOR SIGNS OF REDDISH-BROWN (IRON OXIDE) STAINS. IF STAINS ARE OBSERVED, RETURN THE FUEL PUMP TO NA APPROVED OVERHAUL (TAB 601) (LH)",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "motor1_tso",
   "tipoVenc": "horas",
   "intervalo": 1800,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-018"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "IF SUNDSTRAND FUEL PUMP. REMOVE FUEL PUMP AND INSPECT THE DRIVE COUPLING AND COVER (ACESSORY GEARBOX SIDE) FOR SIGNS OF REDDISH-BROWN (IRON OXIDE) STAINS. IF STAINS ARE OBSERVED, RETURN THE FUEL PUMP TO NA APPROVED OVERHAUL  (TAB 601) (RH)",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "motor2_tso",
   "tipoVenc": "horas",
   "intervalo": 1800,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-019"
  },
  {
   "grupo": "79 - ENGINE LUBRICATING SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "HOSE CARRYING FLAMABLE LIQUIDIS (LH/RH)",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 60,
    "exec": null
   },
   "id": "PX-PRARN-020"
  },
  {
   "grupo": "GRANDES MODIFICAÇÕES",
   "categoria": "celula",
   "unidade": null,
   "nome": "COLETE SALVA VIDAS",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": null
   },
   "id": "PX-PRARN-021"
  },
  {
   "grupo": "28 - AIRCRAFT FUEL SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "FIREWALL SHUTOFF VALVE (LH/RH)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-01"
  },
  {
   "grupo": "28 - AIRCRAFT FUEL SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "WINDSHIELD WIPER BLADE ASSEMBLY",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-02"
  },
  {
   "grupo": "28 - AIRCRAFT FUEL SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "SIDE WINDOWS",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-03"
  },
  {
   "grupo": "28 - AIRCRAFT FUEL SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "WINDSHIELD",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-04"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "ACTUATORS - HYDRAULIC  REVISÃO GERAL",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-05"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": 1,
   "nome": "LOW PRESSURE FUEL BOOST PUMP (LH)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-06"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": 2,
   "nome": "LOW PRESSURE FUEL BOOST PUMP (RH)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-07"
  },
  {
   "grupo": "77 - ENGINE INDICATING SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "TACHOMETER  GENERATOR LH/RH",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-08"
  },
  {
   "grupo": "79 - ENGINE LUBRICATING SYSTEM",
   "categoria": "motor",
   "unidade": 1,
   "nome": "ENGINE OIL (LH) - (TURBO OIL 2380)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-09"
  },
  {
   "grupo": "79 - ENGINE LUBRICATING SYSTEM",
   "categoria": "motor",
   "unidade": 2,
   "nome": "ENGINE OIL (RH) - (TURBO OIL 2380)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-10"
  },
  {
   "grupo": "79 - ENGINE LUBRICATING SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "RADIADOR DE ÓLEO (LH/RH)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-11"
  }
 ]
};
