/* JetFor · patch de itens faltantes por aeronave (idempotente por nome) */
window.JETFOR_PATCH = {
 "PT-LJQ": [
  {
   "grupo": "PHASE 7",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 8",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 6,
    "exec": null
   },
   "id": "PX-PTLJQ-001"
  },
  {
   "grupo": "PHASE 7",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 9",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-002"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 39",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 4500,
   "exec": 4157.1,
   "vencFixo": null,
   "cal": {
    "meses": 36,
    "exec": "2026-06-05"
   },
   "id": "PX-PTLJQ-003"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 40",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 10000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-004"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 43",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 10000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-005"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 46",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 6000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-006"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 47 EXTINTOR CABIN",
   "pn": "C352",
   "sn": "33916237",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 12,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-007"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 47 EXTINTOR PAX",
   "pn": "C352",
   "sn": "1186369",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 12,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-008"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 48",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 6,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-009"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 49",
   "pn": "",
   "sn": "",
   "obs": "ABC TÁXI AÉREO",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 2400,
   "exec": 2325.5,
   "vencFixo": null,
   "id": "PX-PTLJQ-010"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 50",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 15,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-011"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 51",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 10,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-012"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE MB",
   "pn": "",
   "sn": "",
   "obs": "AXIAL",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 10000,
   "exec": 3663,
   "vencFixo": null,
   "id": "PX-PTLJQ-013"
  },
  {
   "grupo": "PHASE 10",
   "categoria": "celula",
   "unidade": null,
   "nome": "VAPOR CYCLE COOLING SYSTEM",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 300,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-014"
  },
  {
   "grupo": "VAPOR CYCLE COOLING SYSTEM COMPRESSOR DRIVE MOTOR BRUSHES",
   "categoria": "motor",
   "unidade": null,
   "nome": "ENVIROMENT CONTROL UNIT (HAMILTON STANDARD)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 5000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-015"
  },
  {
   "grupo": "EXPANSION VALVE - AR CONDICIONADO",
   "categoria": "celula",
   "unidade": null,
   "nome": "MAIN BATTERY",
   "pn": "9914058-6",
   "sn": "12202182",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 100,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-016"
  },
  {
   "grupo": "BATTERY REPLACEMENT",
   "categoria": "celula",
   "unidade": null,
   "nome": "GPS/XM ANTENNA EDDY CURRENT INSPECTION",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 34694,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTLJQ-017"
  },
  {
   "grupo": "ICA SKY899 MM 009-11900-001",
   "categoria": "celula",
   "unidade": null,
   "nome": "SKY899/ANTENA - Seção 4.3",
   "pn": "",
   "sn": "",
   "obs": "AXIAL",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": "2026-05-13"
   },
   "id": "PX-PTLJQ-018"
  },
  {
   "grupo": "ICA WX1000 MM 78-8051-9150-5",
   "categoria": "celula",
   "unidade": null,
   "nome": "SISTEMA STORMSCOPE",
   "pn": "",
   "sn": "",
   "obs": "AXIAL",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": "2026-05-13"
   },
   "id": "PX-PTLJQ-019"
  },
  {
   "grupo": "ICA SSCVR MM 980-6020-011",
   "categoria": "celula",
   "unidade": null,
   "nome": "INSPECTION/CHECK",
   "pn": "",
   "sn": "",
   "obs": "AXIAL",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": "2026-05-13"
   },
   "id": "PX-PTLJQ-020"
  }
 ],
 "PR-ARN": [
  {
   "grupo": "ITENS DE SERVIÇOS GERAIS",
   "categoria": "celula",
   "unidade": null,
   "nome": "EDGELIGHTED PANEL ASSY - INSPECTION",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 2000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-001"
  },
  {
   "grupo": "ITENS DE SERVIÇOS GERAIS",
   "categoria": "celula",
   "unidade": null,
   "nome": "ENGINE FIRE EXTINGUISHER BOTTTLE",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 60,
    "exec": null
   },
   "id": "PX-PRARN-002"
  },
  {
   "grupo": "ITENS DE SERVIÇOS GERAIS",
   "categoria": "celula",
   "unidade": null,
   "nome": "ENGINE FIRE EXTINGUISHER CARTRIDGE (SQUIB)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 72,
    "exec": null
   },
   "id": "PX-PRARN-003"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "ACTUATORS - MECHANICAL (ATUADORES MECÂNICOS) REVISÃO GERAL",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 8000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-004"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "motor",
   "unidade": null,
   "nome": "LANDING GEAR MOTOR - MECHANICAL (MOTOR DO TREM DE POUSO - MECÂNICO)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 8000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-005"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "NOSE AND MAIN LANDING GEAR ACTUATOR - INSPECTION",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 1000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-006"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "NOSE LANDING GEAR ACTUATOR LUBRIFICATION",
   "pn": "112-380022-21",
   "sn": "2581",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 1000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-007"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "MAIN LANDING GEAR ACTUATOR LUBRIFICATION",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 1000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-008"
  },
  {
   "grupo": "52 - DOOR",
   "categoria": "celula",
   "unidade": null,
   "nome": "WINDSHIELD FRAME SCREEWS",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 10000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-009"
  },
  {
   "grupo": "53 - FUSELAGE",
   "categoria": "celula",
   "unidade": null,
   "nome": "FUSELAGE STRINGER INSPECTION (A) (B) (C) (D) (E)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 2500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-010"
  },
  {
   "grupo": "53 - FUSELAGE",
   "categoria": "celula",
   "unidade": null,
   "nome": "FLIGHT CONTROL SYSTEMS WITHIN THE FUSELAGE PRESSURE VESSEL",
   "pn": "",
   "sn": "",
   "obs": "MTX",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 200,
   "exec": 1660.1,
   "vencFixo": null,
   "id": "PX-PRARN-011"
  },
  {
   "grupo": "57 - WINGS",
   "categoria": "celula",
   "unidade": null,
   "nome": "WING CENTER SECTION AND OUTBOARD WING",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 9500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-012"
  },
  {
   "grupo": "57 - WINGS",
   "categoria": "celula",
   "unidade": null,
   "nome": "WING CENTER SECTION",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 18000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-013"
  },
  {
   "grupo": "REPLACE LH/RH OUTBOARD WING SPAR",
   "categoria": "celula",
   "unidade": null,
   "nome": "OUTBOARD WING STRUCTURE",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 30000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-014"
  },
  {
   "grupo": "REPLACE LH/RH OUTBOARD WING SPAR",
   "categoria": "celula",
   "unidade": null,
   "nome": "WING AND ASSOCIATED STRUCTURE FATIGUE SAFELIFE",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 30000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-015"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "IF SUNDSTRAND FUEL PUMP INSTALLED: CHECK FUEL PUMP COUPLING IN-SITU FOR FRETTING AND CORROSION (LH) TABELA 601",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 600,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-016"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "IF SUNDSTRAND FUEL PUMP INSTALLED: CHECK FUEL PUMP COUPLING IN-SITU FOR FRETTING AND CORROSION (RH) TABELA 601",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor2_tsn",
   "tipoVenc": "horas",
   "intervalo": 600,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-017"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "IF SUNDSTRAND FUEL PUMP. REMOVE FUEL PUMP AND INSPECT THE DRIVE COUPLING AND COVER (ACESSORY GEARBOX SIDE) FOR SIGNS OF REDDISH-BROWN (IRON OXIDE) STAINS. IF STAINS ARE OBSERVED, RETURN THE FUEL PUMP TO NA APPROVED OVERHAUL (TAB 601) (LH)",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "motor1_tso",
   "tipoVenc": "horas",
   "intervalo": 1800,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-018"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "IF SUNDSTRAND FUEL PUMP. REMOVE FUEL PUMP AND INSPECT THE DRIVE COUPLING AND COVER (ACESSORY GEARBOX SIDE) FOR SIGNS OF REDDISH-BROWN (IRON OXIDE) STAINS. IF STAINS ARE OBSERVED, RETURN THE FUEL PUMP TO NA APPROVED OVERHAUL  (TAB 601) (RH)",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "motor2_tso",
   "tipoVenc": "horas",
   "intervalo": 1800,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRARN-019"
  },
  {
   "grupo": "79 - ENGINE LUBRICATING SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "HOSE CARRYING FLAMABLE LIQUIDIS (LH/RH)",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 60,
    "exec": null
   },
   "id": "PX-PRARN-020"
  },
  {
   "grupo": "GRANDES MODIFICAÇÕES",
   "categoria": "celula",
   "unidade": null,
   "nome": "COLETE SALVA VIDAS",
   "pn": "-",
   "sn": "-",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": null
   },
   "id": "PX-PRARN-021"
  },
  {
   "grupo": "28 - AIRCRAFT FUEL SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "FIREWALL SHUTOFF VALVE (LH/RH)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-01"
  },
  {
   "grupo": "28 - AIRCRAFT FUEL SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "WINDSHIELD WIPER BLADE ASSEMBLY",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-02"
  },
  {
   "grupo": "28 - AIRCRAFT FUEL SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "SIDE WINDOWS",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-03"
  },
  {
   "grupo": "28 - AIRCRAFT FUEL SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "WINDSHIELD",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-04"
  },
  {
   "grupo": "32 - TREM DE POUSO",
   "categoria": "celula",
   "unidade": null,
   "nome": "ACTUATORS - HYDRAULIC  REVISÃO GERAL",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-05"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": 1,
   "nome": "LOW PRESSURE FUEL BOOST PUMP (LH)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-06"
  },
  {
   "grupo": "73 - ENGINE FUEL SYSTEM",
   "categoria": "motor",
   "unidade": 2,
   "nome": "LOW PRESSURE FUEL BOOST PUMP (RH)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-07"
  },
  {
   "grupo": "77 - ENGINE INDICATING SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "TACHOMETER  GENERATOR LH/RH",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-08"
  },
  {
   "grupo": "79 - ENGINE LUBRICATING SYSTEM",
   "categoria": "motor",
   "unidade": 1,
   "nome": "ENGINE OIL (LH) - (TURBO OIL 2380)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-09"
  },
  {
   "grupo": "79 - ENGINE LUBRICATING SYSTEM",
   "categoria": "motor",
   "unidade": 2,
   "nome": "ENGINE OIL (RH) - (TURBO OIL 2380)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-10"
  },
  {
   "grupo": "79 - ENGINE LUBRICATING SYSTEM",
   "categoria": "motor",
   "unidade": null,
   "nome": "RADIADOR DE ÓLEO (LH/RH)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": null,
   "tipoVenc": "oc",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "id": "OC-PRARN-11"
  }
 ],
 "PR-FHN": [
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 6",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": null
   },
   "id": "PX-PRFHN-001"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 8",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 6,
    "exec": null
   },
   "id": "PX-PRFHN-002"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 9",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-003"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 12",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 3600,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-004"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 22 - TESTE HIDROSTÁTICO - PNEUMATIC STORAGE BOTTLE",
   "pn": "212940-2",
   "sn": "8134",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 36,
    "exec": null
   },
   "id": "PX-PRFHN-005"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 39",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 4500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-006"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 40",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 10000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-007"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 43",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 10000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-008"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 46",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 6000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-009"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 47 EXTINTOR CABIN",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 12,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-010"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 47 EXTINTOR PAX",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 12,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-011"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 48",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 6,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 36,
    "exec": "2024-08-30"
   },
   "id": "PX-PRFHN-012"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 50",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 15,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-013"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 51 - OXYGEN CYLINDER (DOT 3AA)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 10,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-014"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 58",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 300,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-015"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE 59",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-016"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "PHASE MA",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 300,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-017"
  },
  {
   "grupo": "INSPEÇÕES PERIÓDICAS",
   "categoria": "celula",
   "unidade": null,
   "nome": "VAPOR CYCLE COOLING SYSTEM",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 300,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-018"
  },
  {
   "grupo": "VAPOR CYCLE COOLING SYSTEM COMPRESSOR DRIVE MOTOR BRUSHES",
   "categoria": "motor",
   "unidade": null,
   "nome": "ENVIROMENT CONTROL UNIT (HAMILTON STANDARD)",
   "pn": "2201820-1",
   "sn": "119351",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 5000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-019"
  },
  {
   "grupo": "VAPOR CYCLE COOLING SYSTEM COMPRESSOR DRIVE MOTOR BRUSHES",
   "categoria": "motor",
   "unidade": null,
   "nome": "OVERHEAD CABIN FAN",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 1000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-020"
  },
  {
   "grupo": "EXPANSION VALVE - AR CONDICIONADO",
   "categoria": "celula",
   "unidade": null,
   "nome": "MAIN BATTERY",
   "pn": "9914058-6",
   "sn": "12202182",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 100,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-021"
  },
  {
   "grupo": "BATTERY REPLACEMENT",
   "categoria": "celula",
   "unidade": null,
   "nome": "GPS/XM ANTENNA EDDY CURRENT INSPECTION",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 34694,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PRFHN-022"
  }
 ],
 "PT-WHB": [
  {
   "grupo": "B- 6-MONTH INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "1-MAIN BATTERY (SAFT NI-CARD SERIES) (RK-1 THRU RK-97) - PERFOM REGULAR CHECK AS IDENTIFIED IN THE SAFT CMM, CHAPTER 24-30-99 IN THE CMM, P/N 128-590001-81 OR SUBSEQUENT.(TASK 215005)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 6,
    "exec": null
   },
   "id": "PX-PTWHB-001"
  },
  {
   "grupo": "B- 6-MONTH INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "2-EMERGENCY LIGHTING SYSTEM (ONLY FOR BATERIES INSTALLED MORE THAN 3 YEARS)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 6,
    "exec": null
   },
   "id": "PX-PTWHB-002"
  },
  {
   "grupo": "C- 500-HOUR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "1- DRIVE BELT/PULLEY (TASK 210018)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-003"
  },
  {
   "grupo": "C- 500-HOUR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "2- COMPRESSOR/SHAFT SEAL (TASK 210017)",
   "pn": "1134160",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-004"
  },
  {
   "grupo": "C- 500-HOUR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "3- CONDENSER FAN/OUTLET SHROUD (TASK 210019)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-005"
  },
  {
   "grupo": "C- 500-HOUR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "4- CONDENSER COIL (TASK 210020)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-006"
  },
  {
   "grupo": "C- 500-HOUR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "5- ELETRICAL WIRING (TASK 210021)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-007"
  },
  {
   "grupo": "C- 500-HOUR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "8- BELT COVER (TASK 210023)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-008"
  },
  {
   "grupo": "F- ONE YEAR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "1- INDIVIDUAL FLOATATION DEVICE (MODEL NUMBER GA-12) - RECERTIFY DEVICE ONCE A YEAR AFTER BEING PLACED IN SERVICE. (TASK CODE 256030 THRU 256040)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": null
   },
   "id": "PX-PTWHB-009"
  },
  {
   "grupo": "F- ONE YEAR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "2- EMERGENCY LIGHT POWER SUPPLIES (RK-98, RK110 AND AFTER) - PERFORM THE INSPECTION/CHECK OF POWER SUPPLY. REFER TO CHAPTER 33-51-00. (TASK CODE 330006)",
   "pn": "87-5106-2",
   "sn": "",
   "obs": "WS ENG MNT",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": "2025-02-28"
   },
   "id": "PX-PTWHB-010"
  },
  {
   "grupo": "F- ONE YEAR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "3- EMERGENCY LIGHT SYSTEM  (RK-98, RK110 AND AFTER) - PERFORM THE FUNCTIONAL TEST AND BATTERY DISCHARGE TEST. REFER TO CHAPTER 33-51-00. (TASK CODE 330005)",
   "pn": "87-5106-2",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": null
   },
   "id": "PX-PTWHB-011"
  },
  {
   "grupo": "F- ONE YEAR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "4- FLIGHT DATA RECORDER (IF APPLICABLE) - PERFORM THE FLIGHT DATA RECORDER (FDR) INSPECTION CHECK. REFER TO CHAPTER 31-30-00. (TASK CODE 313005)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": null
   },
   "id": "PX-PTWHB-012"
  },
  {
   "grupo": "F- ONE YEAR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "ELT - HEXADECIMAL - INFOSAR",
   "pn": "58C89EC240FFBFF",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 24,
    "exec": null
   },
   "id": "PX-PTWHB-013"
  },
  {
   "grupo": "F- ONE YEAR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "8- MAIN BATTERY (SAFT NI-CAD SERIES) (RK-1 THRU RK-97) - PERFORM GENERAL OVERHAUL AS IDENDIFIED IN THE SAFT CMM. CHAPTER 24-30-99 IN THE CMM P/N 128-590001-81 OR SUBSEQUENT. (TASK CODE 240018)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": null
   },
   "id": "PX-PTWHB-014"
  },
  {
   "grupo": "6- FLIGHT DATA RECORDER UNDERWATER LOCATOR BEACON/DEVICE (TASK CODE 313011)",
   "categoria": "celula",
   "unidade": null,
   "nome": "A-(RK-36 THRU RK-584) F-1000 FDR - FUNCTIONAL TEST. REFER TO THE DUKANE (SEACOM DIVISION) TECHNICAL MANUAL IN CHPTER 23 OF THE CMM, P/N 128-590001-81 OR SUBSEQUENT FOR TEST PROCEDURES.",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 24,
    "exec": null
   },
   "id": "PX-PTWHB-015"
  },
  {
   "grupo": "6- FLIGHT DATA RECORDER UNDERWATER LOCATOR BEACON/DEVICE (TASK CODE 313011)",
   "categoria": "celula",
   "unidade": null,
   "nome": "B-(RK-585 AND AFTER) FA2100 FDR - FUNCTIONAL TEST. REFER TO THE DUKANE (SEACOM DIVISION) TECHNICAL MANUAL IN CHPTER 23 OF THE CMM, P/N 128-590001-81 OR SUBSEQUENT FOR TEST PROCEDURES.",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 24,
    "exec": null
   },
   "id": "PX-PTWHB-016"
  },
  {
   "grupo": "I- FIVE-YEAR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "1-LIFE PRESERVER (MODEL XF-35 - P/N P01074-113) - RECERTIFY PRESERVER EVERY FIVE YEARS AFTER BEING PLACED IN SERVICE. (TASK CODE 256030.1 THRU 250040.1)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 60,
    "exec": null
   },
   "id": "PX-PTWHB-017"
  },
  {
   "grupo": "B-(RK-585 AND AFTER) FA2100 FDR - REPLACE BATTERY. REFER TO THE DUKANE (SEACOM DIVISION) TECHNICAL MANUAL IN CHPTER 23 OF THE CMM, P/N 128-590001-81 OR SUBSEQUENT FOR TEST PROCEDURES.",
   "categoria": "celula",
   "unidade": null,
   "nome": "2-CREW OXYGEN MASK P1 (BE AEROSPACE, SWEEP-ON 2000) - PERFORM OVERHAUL SIX YEARS FROM DATA OF MANUFACTURE OR LAST OVERHAUL (TASK CODE 350006) - COPILOT",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 72,
    "exec": null
   },
   "id": "PX-PTWHB-018"
  },
  {
   "grupo": "B-(RK-585 AND AFTER) FA2100 FDR - REPLACE BATTERY. REFER TO THE DUKANE (SEACOM DIVISION) TECHNICAL MANUAL IN CHPTER 23 OF THE CMM, P/N 128-590001-81 OR SUBSEQUENT FOR TEST PROCEDURES.",
   "categoria": "celula",
   "unidade": null,
   "nome": "2-CREW OXYGEN MASK P2 (BE AEROSPACE, SWEEP-ON 2000) - PERFORM OVERHAUL SIX YEARS FROM DATA OF MANUFACTURE OR LAST OVERHAUL (TASK CODE 350006) - COPILOT",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 72,
    "exec": null
   },
   "id": "PX-PTWHB-019"
  },
  {
   "grupo": "L- TEN-YEAR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "1-SVC-37 FLOATATION VEST (P/N HS3701C) - RECERTIFY VEST EVERY TEN YEARS AFTER BEING PLACED IN SERVICE. (TASK CODE 256030.2 THRU 256040.2)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 120,
    "exec": null
   },
   "id": "PX-PTWHB-020"
  },
  {
   "grupo": "L- TEN-YEAR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "3- PROTECTIVE BREATHING EQUIPMENT (PBE) AVOX SYSTEMS (P/N 802300-14) - Replace every ten years from date of manufacture. (Task Code 350012)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 120,
    "exec": null
   },
   "id": "PX-PTWHB-021"
  },
  {
   "grupo": "R- 4,500-HOURS/3,000- LANDINGS INITIAL AND 1,400-HOURS/ 1,400-LANDINGS SUBSEQUENT INTERVALS (RK-1 THRU RK- 23 WITHOUT KIT 128-8001 INSTALLED)",
   "categoria": "celula",
   "unidade": null,
   "nome": "1- LH MAIN LANDING GEAR RETRACTION CYLINDER (P/N 45AS38515) - Perform Eddy current inspection of the retraction cylinder mounting lug for evidence of cracks in accordance with Chapter 20-80-03. Removal of the spherical bearing is not required. Refer to Figure 40. (Task Code 322113, 322213)",
   "pn": "45AS38515",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 1400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-022"
  },
  {
   "grupo": "R- 4,500-HOURS/3,000- LANDINGS INITIAL AND 1,400-HOURS/ 1,400-LANDINGS SUBSEQUENT INTERVALS (RK-1 THRU RK- 23 WITHOUT KIT 128-8001 INSTALLED)",
   "categoria": "celula",
   "unidade": null,
   "nome": "1- RH MAIN LANDING GEAR RETRACTION CYLINDER (P/N 45AS38515) - Perform Eddy current inspection of the retraction cylinder mounting lug for evidence of cracks in accordance with\nChapter 20-80-03. Removal of the spherical bearing is not required. Refer to Figure 40.(Task Code 322113, 322213)",
   "pn": "45AS38515",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 1400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-023"
  },
  {
   "grupo": "R- 4,500-HOURS/3,000- LANDINGS INITIAL AND 1,400-HOURS/ 1,400-LANDINGS SUBSEQUENT INTERVALS (RK-1 THRU RK- 23 WITHOUT KIT 128-8001 INSTALLED)",
   "categoria": "celula",
   "unidade": null,
   "nome": "2- NOSE LANDING GEAR RETRACTION CYLINDER (P/N45AS39503) - Perform Eddy current inspection of the retraction cylinder mounting lug for evidence of cracks in accordance with\nChapter 20-80-03. Removal of the spherical bearing is not required. Refer to Figure 41.      (Task Code 322013)",
   "pn": "45AS39503 1)",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 1400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-024"
  },
  {
   "grupo": "U. 9,800-HOUR INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "1. AIRBORNE FLIGHT INFORMATION SYSTEM (AFIS) WIRING (RK-483 and After - Optional) - Visually inspect for signs of chafing, security and corrosion. (Task Code 341176)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 9800,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-025"
  },
  {
   "grupo": "W. 12,200-HOUR INITIAL AND 3,600-HOUR SUBSEQUENT INTERVALS",
   "categoria": "celula",
   "unidade": null,
   "nome": "1. AIRBORNE FLIGHT INFORMATION SYSTEM (AFIS) ANTENNA FUSELAGE FEED-THROUGH (FS 378.54 - lower fuselage (RK-483 and After - Optional) - Detail  inspect for corrosion and wear. Using Eddy current method (with a surface probe) inspect for cracks and any indication of structural damage. Antenna removal is required. Refer to Chapter 34-59- 00. (Task Code 341177)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 12200,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-026"
  },
  {
   "grupo": "C. LANDING GEAR - (RK-1 AND AFTER) - Note: For airplanes RK-1 thru RK-23 With Kit 128-8001 Installed",
   "categoria": "celula",
   "unidade": null,
   "nome": "b. (RK-1 thru RK-23 Without Kit 128-8001 Installed) (P/N 45AS38101) - Teardown/Inspect/Repair in accordance with the CMM, P/N 128-590001-81 or subsequent. (Task Code 043202 )",
   "pn": "(lh 45AS38101-001)          (rh 45AS38101-012)",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 3000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-027"
  },
  {
   "grupo": "C. LANDING GEAR - (RK-1 AND AFTER) - Note: For airplanes RK-1 thru RK-23 With Kit 128-8001 Installed",
   "categoria": "celula",
   "unidade": null,
   "nome": "c. (RK-1 thru RK-23 With Kit 128-8001 Installed) - Teardown/ Inspect/ Repair in accordance with the CMM, P/N 128-590001-81 or subsequent. (Task Code 043203)",
   "pn": "(lh 45AS38101-001)          (rh 45AS38101-012)",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 5000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-028"
  },
  {
   "grupo": "2. Main Gear Side Strut LH (P/N 45AS38102, 128-810081)                                                                                                           a. Replace Main Gear Side Strut Assemblies in accordance with Chapter 32-10-00 in the Model 400/400A Maintenance Manual.   (Task Cod 043205)",
   "categoria": "celula",
   "unidade": null,
   "nome": "b. (RK-1 thru RK-23 Without Kit 128-8001 Installed) (P/N 45AS38102) - Teardown/Inspect/Repair in accordance with the CMM, P/N 128-590001-81 or subsequent. (Task Code 043206)",
   "pn": "(lh 45AS38102-003)                (rh 45AS38102-004)",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 3000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-029"
  },
  {
   "grupo": "2. Main Gear Side Strut LH (P/N 45AS38102, 128-810081)                                                                                                           a. Replace Main Gear Side Strut Assemblies in accordance with Chapter 32-10-00 in the Model 400/400A Maintenance Manual.   (Task Cod 043205)",
   "categoria": "celula",
   "unidade": null,
   "nome": "c. (RK-1 thru RK-23 With Kit 128-8001 Installed) - Teardown/ Inspect/  Repair in accordance with the CMM, P/N 128-590001-81 or subsequent. (Task Code 043207)",
   "pn": "(lh 45AS38102-003)                (rh 45AS38102-004)",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 5000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-030"
  },
  {
   "grupo": "2. Main Gear Side Strut RH (P/N 45AS38102, 128-810081)                                                                                                           a. Replace Main Gear Side Strut Assemblies in accordance with Chapter 32-10-00 in the Model 400/400A Maintenance Manual.   (Task Cod 043205)",
   "categoria": "celula",
   "unidade": null,
   "nome": "b. (RK-1 thru RK-23 Without Kit 128-8001 Installed) (P/N 45AS39101) - Teardown/Inspect/ Repair in accordance with the CMM, P/N 128-590001-81 or subsequent. (Task Code 043211)",
   "pn": "45AS39101                  (45200-11)",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 3000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-031"
  },
  {
   "grupo": "2. Main Gear Side Strut RH (P/N 45AS38102, 128-810081)                                                                                                           a. Replace Main Gear Side Strut Assemblies in accordance with Chapter 32-10-00 in the Model 400/400A Maintenance Manual.   (Task Cod 043205)",
   "categoria": "celula",
   "unidade": null,
   "nome": "c. (RK-1 thru RK-23 With Kit 128-8001 Installed) - Teardown/ Inspect/ Repair in accordance with the CMM, P/N 128-590001-81 or subsequent.                             (Task Code 043212)",
   "pn": "45AS39101                  (45200-11)",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 5000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-032"
  },
  {
   "grupo": "2. Main Gear Side Strut RH (P/N 45AS38102, 128-810081)                                                                                                           a. Replace Main Gear Side Strut Assemblies in accordance with Chapter 32-10-00 in the Model 400/400A Maintenance Manual.   (Task Cod 043205)",
   "categoria": "celula",
   "unidade": null,
   "nome": "b. (RK-1 thru RK-23 Without Kit 128-8001 Installed) (P/N 45AS39101) - Teardown/Inspect/Repair in accordance with the CMM, P/N 128-590001-81 or subsequent. (Task Code 043211)",
   "pn": "45AS39101                  (45200-11)",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 3000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-033"
  },
  {
   "grupo": "5. Nose Gear Drag Strut Assembly (P/N 45AS39102, 128-820044)                                                                                                                                                                                               a. Replace Nose Gear Drag Strut Assembly in accordance with Chapter 32-20-00 in the Model 400/400A Maintenance Manual. (Task Code 043214)",
   "categoria": "celula",
   "unidade": null,
   "nome": "b. (RK-1 thru RK-23 Without Kit 128-8001 Installed) (P/N 45AS39102) - Teardown/Inspect/Repair in accordance with the Component Maintenance Manual, P/N 128-590001-81 or subsequent.. (Task Code 043215)",
   "pn": "45AS39102",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 3000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-034"
  },
  {
   "grupo": "5. Nose Gear Drag Strut Assembly (P/N 45AS39102, 128-820044)                                                                                                                                                                                               a. Replace Nose Gear Drag Strut Assembly in accordance with Chapter 32-20-00 in the Model 400/400A Maintenance Manual. (Task Code 043214)",
   "categoria": "celula",
   "unidade": null,
   "nome": "c. (RK-1 thru RK-23 With Kit 128-8001 and 128-8201 Installed) - Teardown/Inspect/Repair in accordance with the CMM, P/N 128-590001-81 or subsequent. (Task Code 043216)",
   "pn": "45AS39102",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 5000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-035"
  },
  {
   "grupo": "5. Nose Gear Drag Strut Assembly (P/N 45AS39102, 128-820044)                                                                                                                                                                                               a. Replace Nose Gear Drag Strut Assembly in accordance with Chapter 32-20-00 in the Model 400/400A Maintenance Manual. (Task Code 043214)",
   "categoria": "celula",
   "unidade": null,
   "nome": "d. (RK-24 and After) (P/N 128-820044) - Teardown/Inspect/Repair in accordance with the CMM, P/N 128-590001-81 or subsequent.                                              (Task Code 043217)",
   "pn": "128-820044-1",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 5000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-036"
  },
  {
   "grupo": "6. Nose Gear Upper Drag Strut Assembly (P/N 128-820026) (RK-1 thru RK-23 installed as a spare, Without Kit 128-8001 Installed)                                                                                                                                                                                              a. Replace Nose Gear Upper Drag Strut Assembly in accordance with Chapter 32-20-00 in the Model 400/400A Maintenance Manual. (Task Code 043218)",
   "categoria": "celula",
   "unidade": null,
   "nome": "b. Teardown/Inspect/Repair in accordance with the Component Maintenance Manual, P/N 128-590001-81 or subsequent                                                               (Task Code 043219)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 3000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-037"
  },
  {
   "grupo": "Engines Minor Inspection - TABLE 601, Periodic Inspection 72-00-00 ( P&WC P/N 3033442) - Rev 49 de 25/10/2021",
   "categoria": "motor",
   "unidade": null,
   "nome": "LH - Compressor Inlet - JT15D-5 (Pre-SB7264 and Pre-SB7369) engines only: inspect LP compressor bypass stator retaining rivets around circumference of LP compressor case. Ensure that all rivets are present and secure.",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor1_tso",
   "tipoVenc": "horas",
   "intervalo": 300,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-038"
  },
  {
   "grupo": "Engines Minor Inspection - TABLE 601, Periodic Inspection 72-00-00 ( P&WC P/N 3033442) - Rev 49 de 25/10/2021",
   "categoria": "motor",
   "unidade": null,
   "nome": "RH - Compressor Inlet - JT15D-5 (Pre-SB7264 and Pre-SB7369) engines only: inspect LP compressor bypass stator retaining rivets around circumference of LP compressor case. Ensure that all rivets are present and secure.",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor2_tso",
   "tipoVenc": "horas",
   "intervalo": 300,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-039"
  },
  {
   "grupo": "Engines Minor Inspection - TABLE 601, Periodic Inspection 72-00-00 ( P&WC P/N 3033442) - Rev 49 de 25/10/2021",
   "categoria": "motor",
   "unidade": null,
   "nome": "LH Overspeed Control Wire Rope, JT15D-5 (Pre-SB7288) - Using a borescope, inspect overspeed control wire rope clevis and ball end-to-cable joints for security:",
   "pn": "Pós-SB7288",
   "sn": "",
   "obs": "",
   "base": "motor1_tso",
   "tipoVenc": "horas",
   "intervalo": 200,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-040"
  },
  {
   "grupo": "Engines Minor Inspection - TABLE 601, Periodic Inspection 72-00-00 ( P&WC P/N 3033442) - Rev 49 de 25/10/2021",
   "categoria": "motor",
   "unidade": null,
   "nome": "RH Overspeed Control Wire Rope, JT15D-5 (Pre-SB7288) - Using a borescope, inspect overspeed control wire rope clevis and ball end-to-cable joints for security:",
   "pn": "Pós-SB7288",
   "sn": "",
   "obs": "",
   "base": "motor2_tso",
   "tipoVenc": "horas",
   "intervalo": 200,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-041"
  },
  {
   "grupo": "RH Oil Change Interval - (Oil quality is to be monitored on-condition and analyzed periodically as observations warrant Ref.72-00-00, SERVICING).",
   "categoria": "motor",
   "unidade": null,
   "nome": "LH/RH Oil Filter Element (noncleanable), JT15D-5 (Post-SB7476 and Post-SB7581) and JT15D-5R Engines - Remove and inspect the oil filter for foreign matter (For JT15D-5 engines: Ref. 79-20-01, OIL FILTER HOUSING - MAINTENANCE PRACTICES),(For JT15D-5R engines: Ref. 79-21-01, OIL FILTER HOUSING - MAINTENANCE PRACTICES). Reject and replace the oil filter if any foreign matter is found.",
   "pn": "7578659AM",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 200,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-042"
  },
  {
   "grupo": "RH Oil Change Interval - (Oil quality is to be monitored on-condition and analyzed periodically as observations warrant Ref.72-00-00, SERVICING).",
   "categoria": "celula",
   "unidade": null,
   "nome": "LH/RH Thermostatic Bypass Valve (JT15D-5R) - Remove and replace thermostatic bypass valve (Ref. 79-21-01)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 4000,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-043"
  },
  {
   "grupo": "RH Oil Change Interval - (Oil quality is to be monitored on-condition and analyzed periodically as observations warrant Ref.72-00-00, SERVICING).",
   "categoria": "motor",
   "unidade": null,
   "nome": "LH/RH - Fuel Filter (JT15D-5R) - Replace fuel filter (Ref. 73-10-13, FUEL FILTER AND IMPENDING BYPASS SWITCH (JT15D-5R) - MAINTENANCE PRACTICES).",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 200,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-044"
  },
  {
   "grupo": "RH Oil Change Interval - (Oil quality is to be monitored on-condition and analyzed periodically as observations warrant Ref.72-00-00, SERVICING).",
   "categoria": "motor",
   "unidade": null,
   "nome": "LH/RH - Fuel Pump Pop-up Indicator (JT15D-5R) - Inspect position of button. If extended, refer to 72-00-00, FAULT ISOLATION. (MINOR)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "motor1_tso",
   "tipoVenc": "horas",
   "intervalo": 200,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-045"
  },
  {
   "grupo": "RH Oil Change Interval - (Oil quality is to be monitored on-condition and analyzed periodically as observations warrant Ref.72-00-00, SERVICING).",
   "categoria": "motor",
   "unidade": null,
   "nome": "LH - Ignition System - Spark Igniters - Pre-SB7210 engines only:\nInstall new spark igniters (Ref. 74-20-02).",
   "pn": "Pós SB 7210",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 50,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-046"
  },
  {
   "grupo": "RH Oil Change Interval - (Oil quality is to be monitored on-condition and analyzed periodically as observations warrant Ref.72-00-00, SERVICING).",
   "categoria": "motor",
   "unidade": null,
   "nome": "RH - Ignition System - Spark Igniters - Pre-SB7210 engines only:\nInstall new spark igniters (Ref. 74-20-02).",
   "pn": "Pós SB 7210",
   "sn": "",
   "obs": "",
   "base": "motor2_tsn",
   "tipoVenc": "horas",
   "intervalo": 50,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-047"
  },
  {
   "grupo": "RH Oil Change Interval - (Oil quality is to be monitored on-condition and analyzed periodically as observations warrant Ref.72-00-00, SERVICING).",
   "categoria": "motor",
   "unidade": null,
   "nome": "LH - Flange 'C' Bolts (Ref. 72-40-01 and 72-70-01) - Replace flange C bolts on engine not incorporing SB7245 (Ref SB 7250)",
   "pn": "Pós SB7245 e                      Pós SB 7250",
   "sn": "",
   "obs": "",
   "base": "motor1_tsn",
   "tipoVenc": "horas",
   "intervalo": 400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-048"
  },
  {
   "grupo": "RH Oil Change Interval - (Oil quality is to be monitored on-condition and analyzed periodically as observations warrant Ref.72-00-00, SERVICING).",
   "categoria": "motor",
   "unidade": null,
   "nome": "RH - Flange 'C' Bolts (Ref. 72-40-01 and 72-70-01) - Replace flange C bolts on engine not incorporing SB7245 (Ref SB 7250)",
   "pn": "Pós SB7245 e                      Pós SB 7250",
   "sn": "",
   "obs": "",
   "base": "motor2_tsn",
   "tipoVenc": "horas",
   "intervalo": 400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-049"
  },
  {
   "grupo": "1. Auxiliary Fuel Tank (RK-1 thru RK-4) (P/N 128-920185-1, 128-920186-1)\na. Contact BC Customer Support for replacement assistance. (Task Code 042801)",
   "categoria": "celula",
   "unidade": null,
   "nome": "2. Auxiliary Fuel Tank (RK-1 thru RK-4) (P/N 128-920185-1, 128-920186-1) - (Task Code 042802) a. (Outer Tank Structure Only) - Inspect for corrosion, fatigue, cracks loose or failed fasteners, and general condition. Use borescope as needed. Refer to Chapter 20-90-00 in the Model 400/400A MM. - 2,600 Hours Initial/ 2,400 Hours Subsequent",
   "pn": "128-920185-1,                          128-920186-1",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 2400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-050"
  },
  {
   "grupo": "1. Auxiliary Fuel Tank (RK-1 thru RK-4) (P/N 128-920185-1, 128-920186-1)\na. Contact BC Customer Support for replacement assistance. (Task Code 042801)",
   "categoria": "celula",
   "unidade": null,
   "nome": "2. Auxiliary Fuel Tank (RK-5 thru RK-57) (P/N 128-920185-7, 128-920186-7) - (Task Code 042803) a. (Outer Tank Structure Only) - Inspect for corrosion, fatigue, cracks loose or failed fasteners, and general condition. Use borescope as needed. Refer to Chapter 20-90-00 in the Model 400/400A MM. - 2,600 Hours Initial/ 2,400 Hours Subsequent",
   "pn": "128-920185-7,                   128-920186-7",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 2400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-051"
  },
  {
   "grupo": "O. BLEED AIR SYSTEM",
   "categoria": "celula",
   "unidade": null,
   "nome": "b. (Airplanes with less than 1,000 hours or have not complied with 1,000 hour inspection) - Inspect for broken wire braiding on the bellows assembly. Replace the bleed air tube assembly if any broken wires are discovered in the braiding on the bellows assembly or if the bellows assembly is ruptured or leaking (Ref. Figure 4 and Figure 5). (Task Code 043601).",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 400,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-052"
  },
  {
   "grupo": "Secureplane Lead acid baterry installation  ICA 290-0432-01",
   "categoria": "celula",
   "unidade": null,
   "nome": "Perform Capacity Check -  Recurring (if last capacity check result =/> 90% repeat check nest 6 month or 1500 Hours; if result was > 90%, but more that 80% repeat next Check with 3 Month or 750 Hours , is result was =/< 80 replace batery)",
   "pn": "RG-380E-40L",
   "sn": "41390791",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 6,
    "exec": null
   },
   "id": "PX-PTWHB-053"
  },
  {
   "grupo": "Freon Air Condition System Installation  ICA-HOF90103",
   "categoria": "celula",
   "unidade": null,
   "nome": "Compressor - Shaft seal inspection to leak    (operation Hours)",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 500,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-054"
  },
  {
   "grupo": "Aft Baggage Compartment Extension ICA-HOF91101",
   "categoria": "celula",
   "unidade": null,
   "nome": "Inspeção visual nos itens realocados",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "celula_horas",
   "tipoVenc": "horas",
   "intervalo": 200,
   "exec": null,
   "vencFixo": null,
   "id": "PX-PTWHB-055"
  },
  {
   "grupo": "Conjunto de parabrisa LH ICA 17-003-MT2901",
   "categoria": "celula",
   "unidade": null,
   "nome": "Inspeção DryView Rain Repellant Coating",
   "pn": "",
   "sn": "",
   "obs": "",
   "base": "calendario",
   "tipoVenc": "calendário",
   "intervalo": null,
   "exec": null,
   "vencFixo": null,
   "cal": {
    "meses": 12,
    "exec": null
   },
   "id": "PX-PTWHB-056"
  }
 ]
};
